Controllers/AdministrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NSTP.Controllers
{
    public class AdministrationController : Controller
    {
        // GET: Administration
        public ActionResult DashBoard()
        {
            return View();
        }
        public ActionResult NSTPSlider()
        {
            return View();
        }
        public ActionResult NSTPNews()
        {
            return View();
        }
    }
}

Controllers/NSTPNewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NSTP_DAL.Data;
using NSTP_DAL.Models;

namespace NSTP.Controllers
{
    public class NSTPNewsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: NSTPNews
        public async Task<ActionResult> Index()
        {
            return View(await db.NSTPNews.ToListAsync());
        }

        // GET: NSTPNews/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NSTPNews nSTPNews = await db.NSTPNews.FindAsync(id);
            if (nSTPNews == null)
            {
                return HttpNotFound();
            }
            return View(nSTPNews);
        }

        // GET: NSTPNews/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NSTPNews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Title,Description,Date,CreatedOn,IsDeleted")] NSTPNews nSTPNews)
        {
            if (ModelState.IsValid)
            {
                db.NSTPNews.Add(nSTPNews);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(nSTPNews);
        }

        // GET: NSTPNews/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NSTPNews nSTPNews = await db.NSTPNews.FindAsync(id);
            if (nSTPNews == null)
            {
                return HttpNotFound();
            }
            return View(nSTPNews);
        }

        // POST: NSTPNews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Title,Description,Date,CreatedOn,IsDeleted")] NSTPNews nSTPNews)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nSTPNews).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(nSTPNews);
        }

        // GET: NSTPNews/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NSTPNews nSTPNews = await db.NSTPNews.FindAsync(id);
            if (nSTPNews == null)
            {
                return HttpNotFound();
            }
            return View(nSTPNews);
        }

        // POST: NSTPNews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            NSTPNews nSTPNews = await db.NSTPNews.FindAsync(id);
            db.NSTPNews.Remove(nSTPNews);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/NSTPTopBreakingNewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NSTP_DAL.Data;
using NSTP_DAL.Models;

namespace NSTP.Controllers
{
    public class NSTPTopBreakingNewsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: NSTPTopBreakingNews
        public async Task<ActionResult> Index()
        {
            return View(await db.NSTPTopBreakingNews.ToListAsync());
        }

        // GET: NSTPTopBreakingNews/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NSTPTopBreakingNews nSTPTopBreakingNews = await db.NSTPTopBreakingNews.FindAsync(id);
            if (nSTPTopBreakingNews == null)
            {
                return HttpNotFound();
            }
            return View(nSTPTopBreakingNews);
        }

        // GET: NSTPTopBreakingNews/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NSTPTopBreakingNews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Title,Description,Date,CreatedOn,IsDeleted")] NSTPTopBreakingNews nSTPTopBreakingNews)
        {
            if (ModelState.IsValid)
            {
                db.NSTPTopBreakingNews.Add(nSTPTopBreakingNews);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(nSTPTopBreakingNews);
        }

        // GET: NSTPTopBreakingNews/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NSTPTopBreakingNews nSTPTopBreakingNews = await db.NSTPTopBreakingNews.FindAsync(id);
            if (nSTPTopBreakingNews == null)
            {
                return HttpNotFound();
            }
            return View(nSTPTopBreakingNews);
        }

        // POST: NSTPTopBreakingNews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Title,Description,Date,CreatedOn,IsDeleted")] NSTPTopBreakingNews nSTPTopBreakingNews)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nSTPTopBreakingNews).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(nSTPTopBreakingNews);
        }

        // GET: NSTPTopBreakingNews/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NSTPTopBreakingNews nSTPTopBreakingNews = await db.NSTPTopBreakingNews.FindAsync(id);
            if (nSTPTopBreakingNews == null)
            {
                return HttpNotFound();
            }
            return View(nSTPTopBreakingNews);
        }

        // POST: NSTPTopBreakingNews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            NSTPTopBreakingNews nSTPTopBreakingNews = await db.NSTPTopBreakingNews.FindAsync(id);
            db.NSTPTopBreakingNews.Remove(nSTPTopBreakingNews);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_BreakingNews.cshtml
@*@model NSTP_DAL.Models.NSTPTopBreakingNews*@
@model NSTP_DAL.Models.NSTPTopBreakingNews
<div class="row">
    <div class="col-sm-3">
        <div>
            @*<p> @Html.DisplayFor(model => model.Description)</p>*@
        </div>
    </div>
    <div class="col-sm-4">
        mmmmmm
    </div>
    <div class="col-sm-3">
        mmmmmm
    </div>
    <div class="col-sm-2">
        mmmmmm
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" id="TopNav">
        <div class="container-fluid" id="BreakingNewsNav">
            
                @Html.Partial("_BreakingNews")
         
        </div>
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("NSTP", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" id="NavLinks">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutAdministration.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" id="TopNav">
        <div class="container-fluid" id="BreakingNewsNav">

            @Html.Partial("_BreakingNews")

        </div>
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("NSTP", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" id="NavLinks">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    
    <div class="container-fluid body-content">
        <div class="row">
            <div class="col-sm-4">
                <div class="sidebar">
                    <ul class="nav navbar-nav" id="NavLinks">
                        <li>@Html.ActionLink("DASHBOARD", "DashBoard", "Administration")</li>
                        <li>@Html.ActionLink("NSTP NEWS", "Index", "NSTPNews")</li>
                        <li>@Html.ActionLink("NSTP TBN", "Index", "NSTPTopBreakingNews")</li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-8">
                @RenderBody()
            </div>
        </div>
        <footer>
            <p>&copy; @DateTime.Now.Year - NSTP</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>